import type { Metadata } from "next";
import "./globals.scss";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";

import ReactQueryClientProvider from "@/components/Providers/ReactQueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Logistic Tracking Management System",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryClientProvider>
          <SessionProvider>
            <link rel="icon" href="/favicon.ico" sizes="any" /> <Toaster />
            {children}
          </SessionProvider>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
